#include "altimu10v5.h"
#include "RTIMULib.h"

#ifdef ALTIMU10v5
altimu10v5_status_t status;
altimu10v5_message_t msg;
int sampleCount = 0;
int sampleRate = 0;
uint64_t rateTimer;
uint64_t displayTimer;
uint64_t now;
RTIMUSettings *settings;
RTIMU *imu;
RTPressure *pressure
void altimu10v5_init() {


    //  using RTIMULib here allows it to use the .ini file generated by RTIMULibDemo.

    *settings = new RTIMUSettings("RTIMULib");

    *imu = RTIMU::createIMU(settings);
    *pressure = RTPressure::createPressure(settings);

    if ((imu == NULL) || (imu->IMUType() == RTIMU_TYPE_NULL)) {
        printf("No IMU found\n");
        exit(1);
    }

    //  This is an opportunity to manually override any settings before the call IMUInit

    //  set up IMU

    imu->IMUInit();

    //  this is a convenient place to change fusion parameters

    imu->setSlerpPower(0.02);
    imu->setGyroEnable(true);
    imu->setAccelEnable(true);
    imu->setCompassEnable(true);

    //  set up pressure sensor

    if (pressure != NULL)
        pressure->pressureInit();

    //  set up for rate timer

    rateTimer = displayTimer = RTMath::currentUSecsSinceEpoch();
}

void altimu10v5_read(telemetry_data_t *td, uint8_t *buf, int buflen) {
        //  poll at the rate recommended by the IMU

        usleep(imu->IMUGetPollInterval() * 1000);

        while (imu->IMURead()) {
            RTIMU_DATA imuData = imu->getIMUData();

            //  add the pressure data to the structure

            if (pressure != NULL)
                pressure->pressureRead(imuData);

            sampleCount++;

            now = RTMath::currentUSecsSinceEpoch();

            //  display 10 times per second

            if ((now - displayTimer) > 100000) {
                printf("Sample rate %d: %s\n", sampleRate, RTMath::displayDegrees("", imuData.fusionPose));

                if (pressure != NULL) {
                    printf("Pressure: %4.1f, height above sea level: %4.1f, temperature: %4.1f\n",
                           imuData.pressure, RTMath::convertPressureToHeight(imuData.pressure), imuData.temperature);
                }

                fflush(stdout);
                displayTimer = now;
            }

            //  update rate every second

            if ((now - rateTimer) > 1000000) {
                sampleRate = sampleCount;
                sampleCount = 0;
                rateTimer = now;
            }
        }
    }
	
	
	td->heading = imuData.fusionPose.z();
	td->altitude = RTMath::convertPressureToHeight(imuData.pressure); 
    td->roll = imuData.fusionPose.x();
	td->pitch = imuData.fusionPose.y(); 
	
	td->fix = 0;
	td->sats = 0;
	td->latitude = 0; 
	td->longitude = 0;
	td->voltage = 0;
	td->ampere = 0;
	td->speed = 0;
}
#endif
